version: '3'

services:

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
  front-end:
    build:
      context: ./../front-end
      dockerfile: ./../front-end/broker-service.dockerfile
    restart: always
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 1