version: '3'

services:

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
  front-end:
    build:
      context: ./../front-end
      dockerfile: ./../front-end/broker-service.dockerfile
    restart: always
    ports:
      - "81:80"
    deploy:
      mode: replicated
      replicas: 1
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      # Set your own details here:
      - TZ=Europe/Kyiv
      - EMAIL=info@mydomain.com
      - URL=validators.almerico.org
        #- SUBDOMAINS= # www,tb
      - VALIDATION=http
      - CERTPROVIDER=zerossl
      # When testing, set the STAGING=true, otherwise you may hit the LetsEncrypt limit of 5 certificate requests per week.
      - STAGING=false
    volumes:
      #- ~/.nginx/:/config/nginx/proxy-confs/
      - ${PWD}/nginx.thingsboard.subdomain.conf:/config/nginx/proxy-confs/thingsboard.subdomain.conf
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped